### ISSUE TITLE
build functionality to update citations in islandora

### ISSUE THREAD

**Issue by ihardy** [WRLC/orcid_task_service#11]

**Comment by dongourley** [comment]
Let me know how you want the citations in the request. I am currently giving you single URL that gets all the works from ORCID:

    "citations": "https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"

Originally, before I realized you could get all the works from one ORCID api call I was giving you an array of URLS:

    "work": [
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/38200592",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/23792779",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141553",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/21735530",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141734",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141552",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/21736035",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141512",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141545",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141563",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141516",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141514",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141520",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141539",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141538",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141685",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141531"
    ]

**Comment by ihardy** [comment]
Lets keep using the single url for all works.

**Comment by ihardy** [comment]
Create MODs for each item in request. Populate MODS template with given name, lastname, title, url. put orcid into the displayform field.

This scheme might need to be modified based on the outcome of #20.

**Comment by ihardy** [comment]
For creating mods, I'm just looking for key fields (eg, title, author, url, orcid) and mapping them known MODS fields in a simple template. This will work for now, but isn't great since it only gets fields I know about right now.

@krebeck are you familiar with the metadata format for describing works in ORCID (example: https://pub.orcid.org/v2.0/0000-0001-5795-7629/work/10141553) is there some kind of orcid to mods xslt  you're aware of? I'd prefer to use something like that over what I'm doing now if possible.

**Comment by ihardy** [comment]
Question for @krebeck: 

I think I need to create a DC datastream as well as a MODS, waht do you think? As an example, this one was created through our API calls (create object, add rels-ext, add sparse MODS). Information like the author name is in the MODS, but not the Islandora item display: https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1593

**Comment by ihardy** [comment]
might be a problem w/the xml parser I'm using, let me see if I can test that before you consider this...

**Comment by krebeck** [comment]
We can always tweak the metadata display so that it's not looking for any
DC fields and switch to the appropriate MODS instead.  Although, when
created via the GUI, any change to the MODS should immediately trigger the
creation of a new DC also via the MODStoDC.xslt file.  I bet there's a
simple drush command to force it.

A

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040

**Comment by ihardy** [comment]
Creating new citations is about done I'd say. We may want to tweak the display rules on the citations in islandora to suit the data we get from orcid.

This profile + citations were built with our API ~ 7 seconds:

https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1637

here are test results:

request
```
curl -X PUT \
  http://localhost:49506/api/islandora/0000-0002-3948-8942 \
  -H 'content-type: application/json' \
  -d '{
        "identifier": {
            "u1": "0000-0002-3948-8942",
            "netid": "nopreply@wrlc.org"
        },
        "authority": {
            "name": {
                "given": "Don",
                "family": "Gourley"
            },
            "titleInfo": {
                "title": "Test (Consultant)"
            }
        },
        "affiliation": {
            "organization": "University Library",
            "position": "Consultant"
        },
        "url": [
            "https:\/\/www.linkedin.com"
        ],
        "note": {
            "history": "Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."
        },
        "citations": "https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"
}'
```

response
```
{"calls": [{"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1637/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1637/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1637/datastream": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1637/datastream": 201}, {"https://auislandora-dev.wrlc.org/islandora/object/auislandora%3Aroot": 200}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1638/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1639/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1640/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1641/relationship": 201}], "computed_status": 201, "citations_created": ["auislandora:1638", "auislandora:1639", "auislandora:1640", "auislandora:1641"], "post_result": [201], "resource_uri": "https://auislandora-dev.wrlc.org/islandora/object/auislandora:1637"}
```

**Comment by ihardy** [comment]
test command:

```
curl -X PUT \
  http://ops.wrlc.org:8080/api/islandora/0000-0002-3948-8942 \
  -H 'content-type: application/json' \
  -d '{
        "identifier": {
            "u1": "0000-0002-3948-8942",
            "netid": "nopreply@wrlc.org"
        },
        "authority": {
            "name": {
                "given": "Don",
                "family": "Gourley"
            },
            "titleInfo": {
                "title": "Don Gourley (Consultant)"
            }
        },
        "affiliation": {
            "organization": "University Library",
            "position": "Consultant"
        },
        "url": [
            "https:\/\/www.linkedin.com\/in\/dongourley"
        ],
        "note": {
            "history": "Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."
        },
        "citations": "https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"
}'
```

**Comment by dongourley** [comment]
It looks like there is something wrong in my PUT request, somewhere around line 1, column 1, char 0?

<pre>
ORCID DEBUG: PUT http://ops.wrlc.org:8181/api/islandora/0000-0002-3948-8942?{"identifier":{"u1":"0000-0002-3948-8942","netid":"gourley@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"},"titleInfo":{"title":"Don Gourley (Consultant)"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https:\/\/www.linkedin.com\/in\/dongourley\/"],"note":{"history":"Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."},"citations":"https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"}

ORCID DEBUG: RESPONSE (500) Traceback (most recent call last):
  File "app/utils/makecalls.py", line 432, in <module>
    main()
  File "app/utils/makecalls.py", line 391, in main
    pid = get_researcher(s, researcher_attrs)
  File "app/utils/makecalls.py", line 97, in get_researcher
    orcid_search_data = response_data = json.loads(orcid_search_request.content.decode('utf-8'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>

**Comment by ihardy** [comment]
Made a few bug fixes, try again?

**Comment by dongourley** [comment]
Looks like it worked: https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1648

I will look closer to see what data elements did/didn't get in there tomorrow

**Comment by ihardy** [comment]
I created tickets #23 and #24 for the changes you asked for. I'll close this one now since the basics are in place.

Ian
