### ISSUE TITLE
created_date set on GET request

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#13]
I just retrieved my ORCID access information, this is what I got:

    [
        {
            "__v": 0,
            "_id": "5a09e05670ed66d9e3e0a96b",
            "access_token": "0e0cf1ef-db61-4209-a294-5123e99df7ce",
            "created_date": "2017-12-19T19:44:59.209Z",
            "expires_in": 631138518,
            "name": "Don Gourley",
            "orcid": "0000-0002-3948-8942",
            "refresh_token": "ab52dbe0-3e85-4a70-aded-a7b40edbb7e4",
            "scope": "/read-limited /activities/update",
            "token_type": "bearer"
        }
    ]

I did it a couple minutes later and the created_date was incremented by a couple of minutes.

**Comment by ihardy** [comment]
give me just a sec to pull these changes in to the branch that's live on ops and update the existing objects...

**Comment by dongourley** [comment]
No rush...I'm just reporting these as I come across them, I'll let you know if anything is holding me up.

**Comment by ihardy** [comment]
OK, fixed:

http://ops.wrlc.org:8181/api/researchers/0000-0002-3948-8942
