### ISSUE TITLE
Make sure publication linkage in AUDRA-IR are preserved when updating u1 identifier in MADS

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#15]
When a MADS researcher profile is updated with a user's ORCiD replacing email as the u1 identifier, we need to update the publications that are linked to the researcher via email in the MODS records.

I understand that due to a bug in the Islandora API POST update  commands this will need to be done by a GET, DELETE, PUT sequence, thereby losing all the versioning on those MODS records. @krebeck suggested an alternative that might be easier and will not affect the MODS records: the ORCiD could be added to the MADS in a "u2" identifier and the linkage to MODS could be done by checking u1 OR u2. He can provide more detail and corrections if I got that idea wrong.

**Comment by ihardy** [comment]
We're doing this by updating mods records to the orcid at the same time that we update a researchers orcid in mads. This preserves existing links, but doesn't preserve the actual ID (which had been email).
