### ISSUE TITLE
syntax error in makecalls.py?

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#31]
I blew away my MADS and MODS in islandora-dev and tried to recreate in order to get the latest citation info from Orcid, and came back with 500 error response that looks like incorrect syntax:

    ORCID DEBUG: PUT http://ops.wrlc.org:8181/api/islandora/0000-0002-3948-8942?{"identifier":{"u1":"0000-0002-3948-8942","netid":"gourley@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"},"titleInfo":{"title":"Don Gourley (Consultant)"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https:\/\/www.linkedin.com\/in\/dongourley\/"],"note":{"history":"Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."},"citations":"https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,41386462,39879823,39879840"}
    ORCID DEBUG: RESPONSE (500)   File "app/utils/makecalls.py", line 390
        r['computed_status'] = 201
                                 ^
    TabError: inconsistent use of tabs and spaces in indentation

**Comment by ihardy** [comment]
@dongourley yes, my mistake. fixed and tested. The result is below, let me know if you want me to delete your profile / citations again:

created: https://auislandora-dev.wrlc.org/islandora/object/auislandora:1685

response:

```
{"resource_uri": "https://auislandora-dev.wrlc.org/islandora/object/auislandora:1685", "calls": [{"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1685/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1685/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1685/datastream": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1685/datastream": 201}, {"https://auislandora-dev.wrlc.org/islandora/object/auislandora%3Aroot": 200}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1686/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1687/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1688/relationship": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object": 201}, {"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1689/relationship": 201}], "computed_status": 201, "result": null, "citations_created": ["auislandora:1686", "auislandora:1687", "auislandora:1688", "auislandora:1689"], "post_result": [201]}

```

**Comment by ihardy** [comment]
^ I deleted all that so you can test again.

**Comment by dongourley** [comment]
thanks...looks good.
