### ISSUE TITLE
Update of existing MADS results in bunch of bad citations

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#32]
I ran my put Orcid script against Stefan's Id. His ID in AUDRA was email address and this correctly changed it to his ORCID. But now there are a bunch of links to citations on his scholar page -- most with bad data or no data.

I'm not sure we need to have citations created when we are adding an ORCID to existing records, we'll probably delete all those test MADS records that Aaron created before the librarians test.

I also noticed that the citations section of the scholar page says **Recent Citations for** ... should the scholar's name come after that heading?

**Comment by ihardy** [comment]
Looks like the problem is with an extra blank u1 id field in Stefan's MADs. I guess having blank on as the 2nd was matching every citation, the Junk ones are old artifacts from testing. I can tell they're not new because their PIDs are lower in sequence than the ones we're creating now.

I deleted the extra u1 and set it back to email to test again, and that worked without creating an extra u1 field.

To protect against this happening, I'll modify the script to delete all existing u1s before an update instead of doing a find + edit like it's doing now.

I'll create a separate ticket for the recent recent citation display issue.

**Comment by ihardy** [comment]
side note, the blank u1 probably got introduced when we were trying to put two u1 fields to match either ORCID or email.

**Comment by krebeck** [comment]
The dev server is not 100% happy with our MADS.  The "Recent Citations for ______" bit is coming from the MADS title field.  Our MADS generated from ORCID have that field, but for some reason it isn't showing up in the MADS editing interface.  So it's invalid for some reason.  When I manually add a title for Don from within the Islandora metadata editor, it shows up just fine.  Compare this working MADS from prod with one of the current non-working MADS from dev:

`<?xml version="1.0"?>
<mads xmlns="http://www.loc.gov/mads/v2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mads="http://www.loc.gov/mads/v2">
  <authority>
    <name type="personal">
      <namePart type="given">Patricia</namePart>
      <namePart type="family">Aufderheide</namePart>
      <namePart type="date"></namePart>
    </name>
    <titleInfo>
      <title>Patricia "Pat" Aufderheide (School of Communication)</title>
    </titleInfo>
  </authority>`

**Comment by ihardy** [comment]
@krebeck the display rule isn't case sensitive is it? on Stefan's MADS on auislandora-dev I see he's got a couple entries for titleInfo.title. Some some have a lowercase and some have an uppercase I:
```
<titleinfo>
  <title>Stefan Kramer (University Library)</title>
</titleinfo>
<titleinfo>
   <title>Stefan Kramer</title>
</titleinfo>
<titleInfo>
  <title>Stefan Kramer</title>
</titleInfo>
```

**Comment by dongourley** [comment]
I just edited Stefan's record, hope that wasn't causing the titleinfo dups you see/saw. I wanted to change his ID back to email to test my put operation on that kind of MADS. It looks like you are not creating citations when you update an existing MADS for ORCID, right? (which is fine, just checking)

**Comment by ihardy** [comment]
Correct, I'm only creating citations for new records right now. 

Might be interesting to add an "import my citations" feature to optionally import citations if the profile has an ORCID.

**Comment by krebeck** [comment]
Don, 
That's exactly what it was.  I thought we caught all of those already.  So "titleInfo" and "namePart" must have that capital letter in the second word.

A

**Comment by dongourley** [comment]
Is it okay if I blow away Stefan's MADS and see how it (and citations) are created from scratch?

**Comment by ihardy** [comment]
Can you wait just a sec? The title-display-case-sensitive problem is getting introduced in the MADS creation. Trying to fix it quick now. Will update when ready.

**Comment by dongourley** [comment]
that's fine, no rush (pls don't rush ;)
