### ISSUE TITLE
Build routes/controllers to make islandora api calls for create / update researcher

### ISSUE THREAD

**Issue by ihardy** [WRLC/orcid_task_service#4]
reference: https://github.com/WRLC/ORCID-Create-on-demand/issues/4

**Comment by dongourley** [comment]
Here is a sample JSON document that describe's Stefan's ORCID record. Will this work for you to create/update the MADS document in Islandora? 

https://drive.google.com/a/wrlc.org/file/d/1id3S3JRKFcevUfUCNWVJFJDcqz0tOaiU/view?usp=sharing

When looking at the "works" registered in ORCID, I realized that they don't require the authorization of the user to read and it might be simpler for you to get that info directly from ORCID, so I just included the public API URIs for each publication. Note that GETting these URLs by default produces XML; if you want JSON you need to specify an Accept header, e.g.:
`
curl -H 'Accept: application/json' 'https://pub.orcid.org/v2.0/0000-0001-5795-7629/work/38200592'
`
(Note that you would use these URIs to create citation MODS objects linked to the user's MADS object.)

**Comment by ihardy** [comment]
calls for the first part (create or update a person & related datastreams) are running on branch t4. 

~~Currently working on function to modify MADS file before posting (It's just posting the template right now).~~
added in commit: https://github.com/WRLC/orcid_task_service/commit/31f75cfc06eaddb04fe196373e9fb7b29087e139

### sample request

```curl
curl -X PUT \
  http://ops.wrlc.org:8181/api/islandora/12345-12345-12345 \
  -H 'content-type: application/json' \
  -d '{
    "identifier": {
        "u1": "0000-0001-5795-7629",
        "netid": "test@person.edu"
    },
    "authority": {
        "name": {
            "given": "thrityeight",
            "family": "person"
        }
    },
    "affiliation": {
        "email": "fake@email.au",
        "organization": "University Library",
        "position": "Associate Director for Research Data Services"
    },
    "url": [
        "http:\/\/www.linkedin.com\/in\/kramerstefan",
        "http:\/\/www.american.edu\/profiles\/faculty\/skramer.cfm"
    ],
    "note": {
        "history": ""
    },
    "work": [
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/38200592",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/23792779",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141553",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/21735530",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141734",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141552",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/21736035",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141512",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141545",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141563",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141516",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141514",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141520",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141539",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141538",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141685",
        "https:\/\/pub.orcid.org\/v2.0\/0000-0001-5795-7629\/work\/10141531"
    ]
}'
```
Response will be a json object showing the url's that the script made api calls along with their response codes.

### Sample response:

```json
{
    "calls": [
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/rest\/v1\/object": 201
        },
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/rest\/v1\/object\/auislandora:1538\/relationship": 201
        },
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/rest\/v1\/object\/auislandora:1538\/relationship": 201
        },
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/rest\/v1\/object\/auislandora:1538\/datastream": 201
        },
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/rest\/v1\/object\/auislandora:1538\/datastream": 201
        },
        {
            "http:\/\/auislandora-dev.wrlc.org\/islandora\/object\/auislandora%3Aroot": 200
        }
    ]
}
```

**Comment by ihardy** [comment]
@dongourley pushed to following changes to this branch (live at ops):

- return 201 on success 500 if I failed to update the object
- add link to researcher page in response (json key is resource_uri)
- replace MADS with updated orcid if reseracher exists

The replace MADS function is not ideal. It deletes the original, and then posts up a modified copy. The big drawback is that you lose the history. I'm asking Aaron to submit a ticket to DGI to see if it's possible to do a true update.

**Comment by dongourley** [comment]
I am at a point that I can test failure and with an invalid request I got a 500 response. But the body was HTML, not json? Did you generate that or did some pythonny thing? The error was "TypeError: Cannot read property &#39;netid&#39;" (that is, I did not include a netid in my request).

**Comment by ihardy** [comment]
When there's an error that I didn't account for the express router will respond (in HTML) I can see if I can get it to do JSON instead. 

error below for reference

```
PUT /islandora/0000-0002-3948-8942
TypeError: Cannot read property 'netid' of undefined
    at exports.islandora_create_or_update (/opt/local/orcid_task_service/app/controllers/islandora.js:32:22)
    at Layer.handle [as handle_request] (/opt/local/orcid_task_service/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/local/orcid_task_service/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/local/orcid_task_service/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/local/orcid_task_service/node_modules/express/lib/router/layer.js:95:5)
    at /opt/local/orcid_task_service/node_modules/express/lib/router/index.js:281:22
    at param (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:354:14)
    at param (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:410:3)
    at next (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:275:10)
    at /opt/local/orcid_task_service/app/routes/routes.js:13:9
    at Layer.handle [as handle_request] (/opt/local/orcid_task_service/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:317:13)
    at /opt/local/orcid_task_service/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:174:3)
    at router (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/opt/local/orcid_task_service/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:317:13)
    at /opt/local/orcid_task_service/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/local/orcid_task_service/node_modules/express/lib/router/index.js:335:12)
```

**Comment by dongourley** [comment]
I PUT what I think is a valid resource but got a 500 error. This occurred at about 9:42 this morning. Can you look in your logs and see if you can tell what I'm doing wrong?  Here is my log:

ORCID DEBUG: PUT http://ops.wrlc.org:8181/api/islandora/0000-0002-3948-8942?{"identifier":{"u1":"0000-0002-3948-8942","netid":"gourley@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https:\/\/www.linkedin.com\/in\/dongourley\/"]}
PHP Notice:  Undefined offset: 1 in /var/www/ORCID-Create-on-demand/include/jsonapi.php on line 36
cURL Error:  Empty reply from server (52)
ORCID DEBUG: RESPONSE (500) {"status":500,"error":"Empty reply from server (52)"}

Here's line 36 in my program -- so maybe I'm setting the request header incorrectly?

        // Set cURL options for madsdb
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            'Content-Length: ' . strlen($mads))
        );

**Comment by ihardy** [comment]
I think the problem is I'm looking for the JSON data in the body of the request and not the querystring. Maybe something like below?

    // Set cURL options for madsdb
    curl_setopt($ch, CURLOPT_POSTFIELDS, $yourjson);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Content-Length: ' . strlen($mads))
    );

**Comment by dongourley** [comment]
I am doing the CURLOPT_POSTFIELDS, I just put it in the querystring for logging. I'm doing the same PHP put request code that works for PUTting ORCID access token to the researchers endpoint.  

Did you see any error on your end? Could it have timed out? I tried again and timed it and it took exactly 2 minutes to get the "empty response" error (which is a curl error -- not yours). Now that I say that, it must be my curl lib that is timing out waiting for a response from you. I'll try extending that time, although based on your testing it shouldn't take that long, should it?

**Comment by ihardy** [comment]
Shouldn't take that long, I don't think you need to increase the timeout on your end, but I should put on in place on mine. In my testing it takes ~ 3 seconds to create a new person, and less time to update the orcid. 

There are no errors in the webserver log which probably means that the api is calling the script to make the islandora calls, and that script is not coming back. can I run your program for debugging?

**Comment by dongourley** [comment]
Sure, it is at islandora:/var/www/ORCID-Create-on-demand/test/putOrcidRecord.php . You run it from the command line, not web.

You can copy and modify if you want ... although you can't move your copy somewhere else without changing the path to some include files.

**Comment by dongourley** [comment]
I tried submitting my ORCID record via curl command line (not the PHP script) and got the same result: empty response after exactly 2 minutes:

> date ; curl -X PUT http://ops.wrlc.org:8181/api/islandora/0000-0002-3948-8942 -H 'content-type: application/json' -d '{"identifier":{"u1":"0000-0002-3948-8942","netid":"gourley@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https://www.linkedin.com/in/dongourley/"]}' ; date

Thu Dec 21 08:28:12 EST 2017
curl: (52) Empty reply from server
Thu Dec 21 08:30:12 EST 2017

**Comment by ihardy** [comment]
That curl request should work now, can you try again?

To delete the object when you want to repeat the call for testing, go to the object / delete:

https://auislandora-dev.wrlc.org/islandora/object/auislandora:1557/delete

**Comment by dongourley** [comment]
I tried and it worked...201 response in 10s. However, it does not look like you are populating all the MADS fields (comparing what my profile looks compared to Stefan's). It doesn't look like you are mapping these (some are missing in my example request):

    "authority"
        "titleInfo"
            "title" (Name)
    "affiliation"
        "organization" (Department(s))
        "position" (Position)
    "url" (URL)
    "history" (Biography)

Note that these fields (and the ones it looks like you are mapping correctly like authority-name and affiliation-email) should only be used on create...the only thing to update on an existing record is Identifier.

**Comment by ihardy** [comment]
added mappings for all those listed above: https://github.com/WRLC/orcid_task_service/commit/87449f9917c4cb77f6352a1641e3244178af3af4

Update only changes identifier.u1 to orcid.

**Comment by dongourley** [comment]
I deleted Don Gourley records and then PUT a new request that had title, affiliation, url and history data. The "title" did not get into the Name display (it looks like "position" is repeated there) and "history" did not get into the Biography.

I made a mistake in my description of how the "history" is passed to you in the request. It will be under a "note" element. See the full request JSON that I will pretty-print-paste below.

Compare the display of my record with Stefan's...I am basing my request content on his record and basing my request syntax on his MADS record.

Stefan: https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1509

Me: https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1569

    {
        "04-Jan-2018:10:22:09": {
            "identifier": {
                "u1": "0000-0002-3948-8942",
                "netid": "gourley@american.edu"
            },
            "authority": {
                "name": {
                    "given": "Don",
                    "family": "Gourley"
                },
                "titleInfo": {
                    "title": "Don Gourley (Consultant)"
                }
            },
            "affiliation": {
                "organization": "University Library",
                "position": "Consultant"
            },
            "url": [
                "https:\/\/www.linkedin.com\/in\/dongourley\/"
            ],
            "note": {
                "history": "Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."
            },
            "citations": "https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"
        }
    }

**Comment by dongourley** [comment]
When I PUT a request for an ORCID where there is an existing MADS profile -- with either an email or an orcid as the u1 identifier -- I get the empty response / timeout cURL error that we saw before:

    cURL Error:  Empty reply from server (52)

**Comment by ihardy** [comment]
@dongourley to be clear, this is not the actual json format you're sending me correct: https://github.com/WRLC/orcid_task_service/issues/4#issuecomment-355316626? With a timestamp as the first key. 

I'm fixing these issues, but I'm still expecing the request to com in lookin like the example in this comment: https://github.com/WRLC/orcid_task_service/issues/4#issuecomment-353351689

**Comment by dongourley** [comment]
That is correct, I pasted from my log file -- the actual request body is:

`{"identifier":{"u1":"0000-0002-3948-8942","netid":"gourley@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"},"titleInfo":{"title":"Don Gourley (Consultant)"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https:\/\/www.linkedin.com\/in\/dongourley\/"],"note":{"history":"Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."},"citations":"https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"}`

**Comment by ihardy** [comment]
## updates on some of the above issues

1. History Field Mapping: fixed in commit: https://github.com/WRLC/orcid_task_service/commit/4f192791a6e353aca322af74884b66b603d1286d
2. Name / titleInfo display: fixed in commit: https://github.com/WRLC/orcid_task_service/commit/baaec3a5ee55c66ea09a5de59a0138e6ea949c93
3. Update with email identifier: Tested by deleting email from https://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1571, and sending a put request with the data above (email changed). 

Sent:
```bash
curl -X PUT http://ops.wrlc.org:8181/api/islandora/0000-0002-3948-8942 -H 'content-type: application/json' -d '{"identifier":{"u1":"0000-0002-3948-0000","netid":"threetesttesttest@american.edu"},"authority":{"name":{"given":"Don","family":"Gourley"},"titleInfo":{"title":"Don Gourley (Consultant)"}},"affiliation":{"organization":"University Library","position":"Consultant"},"url":["https:\/\/www.linkedin.com\/in\/dongourley\/"],"note":{"history":"Don works with research libraries in the Washington, DC metro area in data management and infrastructure. Don has over 20 years experience directing and managing information technology projects for government and research organizations."},"citations":"https:\/\/pub.orcid.org\/v2.0\/0000-0002-3948-8942\/works\/39879757,39879734,39879823,39879840"}'
```
received:
```json
{"resource_uri": "https://auislandora-dev.wrlc.org/islandora/object/auislandora:1571", "computed_status": 201, "calls": [{"https://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1571/datastream": 201}]}
```
4. Update with Orcid. Looking for existing researchers by email only right now. let me stop by and ask you about this one.
