### ISSUE TITLE
Connection to api/researchers fails

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#42]
ORCID ERROR: http://api.wrlc.org:8181/api/researchers/0000-0002-3948-8942 returned (500) 

Do I have the wrong connection information, or do you need to do something on your end?
See https://servicedesk.wrlc.org/Ticket/Display.html?id=17940

```
{
    "status":500,
    "error":"Failed to connect to api.wrlc.org port 8181: Connection refused (7)"
}
```

**Comment by ihardy** [comment]
Try again? I think I messed up the process manager and it didn't survive reboot. I'm trying a different one and I put the startup command in /etc/rc.local

**Comment by dongourley** [comment]
Thanks, that works now. Also, I rebooted wrphp and verified that the service started up okay. So we can consider this service in production.
