### ISSUE TITLE
merge create & update calls?

### ISSUE THREAD

**Issue by dongourley** [WRLC/orcid_task_service#5]
I'm not sure how to tell whether a request will be an update or a create, without an extra GET request to look up an orcid. What if the syntax for both was http://ops.wrlc.org:8181/api/researchers/<orcid> and you had to figure out if it is a new <orcid> or an update?

**Comment by dongourley** [comment]
Sorry, I didn't read your email carefully and misinterpreted the request syntax. I see now that you meant literal 'orcid' path, not the user's orcid id as part of the path. So the only difference between an update and create is PUT vs. POST? How do I know when to do one or the other?

**Comment by ihardy** [comment]
well, you put when you want to update and post when you want to create ;). 

I see your point though, I think I could modify the function that get's called when you do a post to create or update if exists (assuming this is the desired behaviour).

**Comment by dongourley** [comment]
I think that is (my) desired behavior...but I think it should be a PUT operation, not POST, and should include the ORCiD ID in the path. See https://restfulapi.net/rest-put-vs-post/

(As I read it, a POST would create another access token for a given orcid...not replace/update the existing one.)

**Comment by dongourley** [comment]
Also, could you return a non-200 response code when not successful? For example, when I tried to send you an array rather than string, I got a 200 with this payload:

`{"errors":{"orcid":{"message":"Path `orcid` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"orcid"},"kind":"required","path":"orcid","$isValidatorError":true}},"_message":"Researcher validation failed","message":"Researcher validation failed: orcid: Path `orcid` is required.","name":"ValidationError"}`

If that was a 404 or something, it would make it easier for me to check the result.

**Comment by ihardy** [comment]
The PUT operation should already require the ORCID in the path, but my example in the email wasn't clear. An example path would be put /researchers/12345-12345-12345 where 123.. is the ORCID. see: https://github.com/WRLC/orcid_task_service/blob/master/app/routes/routes.js#L22

I updated the error response to change the response code to 400. Hopefully I'll get a little smarter about error handling and add some more nuance as I get more familiar with express.

**Comment by ihardy** [comment]
I think the problems here are addressed by:

1. but I think it should be a PUT operation, not POST, and should include the ORCiD ID in the path : https://github.com/WRLC/orcid_task_service/pull/9
2. Better errors: https://github.com/WRLC/orcid_task_service/commit/5bd9b531642ee5ec7ea4a40c8d2a9253a5e846ed, https://github.com/WRLC/orcid_task_service/commit/c2fea616b85c9a2aa0db549f86b6008e772b1eba

I'll close this but @dongourley reopen it if there something outstanding please re-open.
